# One source of truth for the encoder test: each case carries the GNU-as text
# and the equivalent Nix encoder call. `asm` is fed to riscv32-none-elf-as and
# `word` is what our encoder produced; the harness diffs them.
let
  e = import ./encode.nix;
  c = asm: word: { inherit asm word; };
in [
  # I-type, including the negative-immediate path
  (c "addi a0, a1, 5"        (e.addi "a0" "a1" 5))
  (c "addi a0, a1, -5"       (e.addi "a0" "a1" (-5)))
  (c "addi x0, x0, 0"        (e.addi "x0" "x0" 0))
  (c "addi t0, sp, 2047"     (e.addi "t0" "sp" 2047))
  (c "addi t0, sp, -2048"    (e.addi "t0" "sp" (-2048)))
  (c "xori a3, a4, -1"       (e.xori "a3" "a4" (-1)))
  (c "andi s0, s1, 255"      (e.andi "s0" "s1" 255))
  (c "sltiu a0, a0, 1"       (e.sltiu "a0" "a0" 1))
  # R-type
  (c "add a0, a1, a2"        (e.add "a0" "a1" "a2"))
  (c "sub s2, s3, s4"        (e.sub "s2" "s3" "s4"))
  (c "and t0, t1, t2"        (e.and "t0" "t1" "t2"))
  (c "or ra, sp, gp"         (e.or "ra" "sp" "gp"))
  (c "xor x31, x30, x29"     (e.xor 31 30 29))
  (c "sll a0, a1, a2"        (e.sll "a0" "a1" "a2"))
  (c "sra a0, a1, a2"        (e.sra "a0" "a1" "a2"))
  (c "slt a0, a1, a2"        (e.slt "a0" "a1" "a2"))
  # shift-immediate (funct7 discriminates srli/srai)
  (c "slli a0, a1, 0"        (e.slli "a0" "a1" 0))
  (c "slli a0, a1, 31"       (e.slli "a0" "a1" 31))
  (c "srli a0, a1, 1"        (e.srli "a0" "a1" 1))
  (c "srai a0, a1, 31"       (e.srai "a0" "a1" 31))
  # loads / stores, negative offsets exercise the split S-type immediate
  (c "lw a0, 0(sp)"          (e.lw "a0" "sp" 0))
  (c "lw a0, -4(sp)"         (e.lw "a0" "sp" (-4)))
  (c "lb a1, 2047(gp)"       (e.lb "a1" "gp" 2047))
  (c "lbu a1, -2048(gp)"     (e.lbu "a1" "gp" (-2048)))
  (c "sw a0, 0(sp)"          (e.sw "a0" "sp" 0))
  (c "sw ra, -4(sp)"         (e.sw "ra" "sp" (-4)))
  (c "sb a2, 1(a3)"          (e.sb "a2" "a3" 1))
  (c "sh a2, -1(a3)"         (e.sh "a2" "a3" (-1)))
  # B-type: the shuffled, scaled-by-2 immediate is the classic encoding trap
  (c "beq a0, a1, ."         (e.beq "a0" "a1" 0))
  (c "bne a0, a1, .+4"       (e.bne "a0" "a1" 4))
  (c "blt a0, a1, .-4"       (e.blt "a0" "a1" (-4)))
  (c "bge a0, a1, .+2046"    (e.bge "a0" "a1" 2046))
  (c "bltu a0, a1, .-2048"   (e.bltu "a0" "a1" (-2048)))
  (c "bgeu a0, a1, .+4094"   (e.bgeu "a0" "a1" 4094))
  (c "beq a0, a1, .-4096"    (e.beq "a0" "a1" (-4096)))
  # U-type
  (c "lui a0, 0"             (e.lui "a0" 0))
  (c "lui a0, 1"             (e.lui "a0" 1))
  (c "lui a0, 0xfffff"       (e.lui "a0" 1048575))
  (c "auipc ra, 0x12345"     (e.auipc "ra" 74565))
  # J-type: another shuffled immediate
  (c "jal ra, ."             (e.jal "ra" 0))
  (c "jal ra, .+4"           (e.jal "ra" 4))
  (c "jal x0, .-4"           (e.jal "x0" (-4)))
  (c "jal ra, .+1048574"     (e.jal "ra" 1048574))
  (c "jal ra, .-1048576"     (e.jal "ra" (-1048576)))
  (c "jalr ra, 0(a0)"        (e.jalr "ra" "a0" 0))
  (c "jalr x0, -8(ra)"       (e.jalr "x0" "ra" (-8)))
  # system
  (c "fence iorw, iorw"      (e.fence 15 15))
  (c "fence rw, rw"          (e.fence 3 3))
  (c "fence r, w"            (e.fence 2 1))
  (c "ecall"                 e.ecall)
  (c "ebreak"                e.ebreak)
  # --- gaps found by mutation testing: these six survived deliberate funct3
  # corruption because nothing exercised them ---
  (c "slti a0, a1, -1"       (e.slti "a0" "a1" (-1)))
  (c "sltu a0, a1, a2"       (e.sltu "a0" "a1" "a2"))
  (c "ori a0, a1, 1365"      (e.ori "a0" "a1" 1365))
  (c "srl a0, a1, a2"        (e.srl "a0" "a1" "a2"))
  (c "lh a0, 4(sp)"          (e.lh "a0" "sp" 4))
  (c "lhu a0, -6(sp)"        (e.lhu "a0" "sp" (-6)))
  # S-type at its bounds: -2048 sets only bit 11, isolating the placement of
  # the high half of the split immediate (bits 11:5 -> 31:25)
  (c "sw a0, 2047(sp)"       (e.sw "a0" "sp" 2047))
  (c "sw a0, -2048(sp)"      (e.sw "a0" "sp" (-2048)))
  (c "sb a0, 2047(sp)"       (e.sb "a0" "sp" 2047))
  (c "sh a0, -2048(sp)"      (e.sh "a0" "sp" (-2048)))
]
++ [
  # every register name, listed explicitly rather than read from the encoder's
  # own table, so a missing name fails as well as a wrong one
  (c "addi x0, zero, 0" (e.addi "x0" "zero" 0))
  (c "addi x1, zero, 0" (e.addi "x1" "zero" 0))
  (c "addi x2, zero, 0" (e.addi "x2" "zero" 0))
  (c "addi x3, zero, 0" (e.addi "x3" "zero" 0))
  (c "addi x4, zero, 0" (e.addi "x4" "zero" 0))
  (c "addi x5, zero, 0" (e.addi "x5" "zero" 0))
  (c "addi x6, zero, 0" (e.addi "x6" "zero" 0))
  (c "addi x7, zero, 0" (e.addi "x7" "zero" 0))
  (c "addi x8, zero, 0" (e.addi "x8" "zero" 0))
  (c "addi x9, zero, 0" (e.addi "x9" "zero" 0))
  (c "addi x10, zero, 0" (e.addi "x10" "zero" 0))
  (c "addi x11, zero, 0" (e.addi "x11" "zero" 0))
  (c "addi x12, zero, 0" (e.addi "x12" "zero" 0))
  (c "addi x13, zero, 0" (e.addi "x13" "zero" 0))
  (c "addi x14, zero, 0" (e.addi "x14" "zero" 0))
  (c "addi x15, zero, 0" (e.addi "x15" "zero" 0))
  (c "addi x16, zero, 0" (e.addi "x16" "zero" 0))
  (c "addi x17, zero, 0" (e.addi "x17" "zero" 0))
  (c "addi x18, zero, 0" (e.addi "x18" "zero" 0))
  (c "addi x19, zero, 0" (e.addi "x19" "zero" 0))
  (c "addi x20, zero, 0" (e.addi "x20" "zero" 0))
  (c "addi x21, zero, 0" (e.addi "x21" "zero" 0))
  (c "addi x22, zero, 0" (e.addi "x22" "zero" 0))
  (c "addi x23, zero, 0" (e.addi "x23" "zero" 0))
  (c "addi x24, zero, 0" (e.addi "x24" "zero" 0))
  (c "addi x25, zero, 0" (e.addi "x25" "zero" 0))
  (c "addi x26, zero, 0" (e.addi "x26" "zero" 0))
  (c "addi x27, zero, 0" (e.addi "x27" "zero" 0))
  (c "addi x28, zero, 0" (e.addi "x28" "zero" 0))
  (c "addi x29, zero, 0" (e.addi "x29" "zero" 0))
  (c "addi x30, zero, 0" (e.addi "x30" "zero" 0))
  (c "addi x31, zero, 0" (e.addi "x31" "zero" 0))
  (c "addi zero, zero, 0" (e.addi "zero" "zero" 0))
  (c "addi ra, zero, 0" (e.addi "ra" "zero" 0))
  (c "addi sp, zero, 0" (e.addi "sp" "zero" 0))
  (c "addi gp, zero, 0" (e.addi "gp" "zero" 0))
  (c "addi tp, zero, 0" (e.addi "tp" "zero" 0))
  (c "addi t0, zero, 0" (e.addi "t0" "zero" 0))
  (c "addi t1, zero, 0" (e.addi "t1" "zero" 0))
  (c "addi t2, zero, 0" (e.addi "t2" "zero" 0))
  (c "addi s0, zero, 0" (e.addi "s0" "zero" 0))
  (c "addi fp, zero, 0" (e.addi "fp" "zero" 0))
  (c "addi s1, zero, 0" (e.addi "s1" "zero" 0))
  (c "addi a0, zero, 0" (e.addi "a0" "zero" 0))
  (c "addi a1, zero, 0" (e.addi "a1" "zero" 0))
  (c "addi a2, zero, 0" (e.addi "a2" "zero" 0))
  (c "addi a3, zero, 0" (e.addi "a3" "zero" 0))
  (c "addi a4, zero, 0" (e.addi "a4" "zero" 0))
  (c "addi a5, zero, 0" (e.addi "a5" "zero" 0))
  (c "addi a6, zero, 0" (e.addi "a6" "zero" 0))
  (c "addi a7, zero, 0" (e.addi "a7" "zero" 0))
  (c "addi s2, zero, 0" (e.addi "s2" "zero" 0))
  (c "addi s3, zero, 0" (e.addi "s3" "zero" 0))
  (c "addi s4, zero, 0" (e.addi "s4" "zero" 0))
  (c "addi s5, zero, 0" (e.addi "s5" "zero" 0))
  (c "addi s6, zero, 0" (e.addi "s6" "zero" 0))
  (c "addi s7, zero, 0" (e.addi "s7" "zero" 0))
  (c "addi s8, zero, 0" (e.addi "s8" "zero" 0))
  (c "addi s9, zero, 0" (e.addi "s9" "zero" 0))
  (c "addi s10, zero, 0" (e.addi "s10" "zero" 0))
  (c "addi s11, zero, 0" (e.addi "s11" "zero" 0))
  (c "addi t3, zero, 0" (e.addi "t3" "zero" 0))
  (c "addi t4, zero, 0" (e.addi "t4" "zero" 0))
  (c "addi t5, zero, 0" (e.addi "t5" "zero" 0))
  (c "addi t6, zero, 0" (e.addi "t6" "zero" 0))
]
